blank_issues_enabled: false
contact_links:
  - name: Ask a question or start a discussion
    url: https://github.com/adenaufal/shollu-modern/discussions
    about: Ask questions or discuss ideas with the community.
